import { tpms } from '@dry/sdk';

// A gyroid TPMS infill block, generated by the engine and returned as a Design.
tpms({ surface: 'gyroid', cellSize: 10, cellsX: 2, cellsY: 2, cellsZ: 1, layerHeight: 0.2 });
