//! ABB RAPID Robot Program Emission.
//!
//! Generates modular, standard ABB RAPID code (`.mod`) with robtarget positions,
//! quaternion orientations `[q1, q2, q3, q4]`, speeddata, zonedata,
//! and MoveL / MoveC instructions.
//!
//! For `MoveC`, ABB defines the first robtarget as `CirPoint`: a point on the circular path,
//! not the circle centre. Dry derives that point from the IR centre and direction. The emitter
//! performs exact representability checks here; tolerance-bearing radius validation remains the
//! verifier/resolver's responsibility and must run before emission.

use super::kinematics::unit_orientation;
use super::EmitParams;
use crate::codec::CodecError;
use crate::ir::{Segment, SegmentKind};
use std::io::Write;

/// Convert a 3D unit direction vector to a quaternion [w, x, y, z] (representing rotation from \[0,0,1\]).
pub fn quaternion_from_direction(dir: [f64; 3]) -> [f64; 4] {
    let [dx, dy, dz] = dir;
    if dz > 0.999999 {
        [1.0, 0.0, 0.0, 0.0]
    } else if dz < -0.999999 {
        [0.0, 1.0, 0.0, 0.0]
    } else {
        let w = 1.0 + dz;
        let x = -dy;
        let y = dx;
        let z = 0.0;
        let norm = (w * w + x * x + y * y + z * z).sqrt();
        [w / norm, x / norm, y / norm, z / norm]
            .map(|component| if component == 0.0 { 0.0 } else { component })
    }
}

/// The signed angle swept from `start` to `end` about an arc centre, in radians.
fn signed_sweep(start: f64, end: f64, clockwise: bool) -> f64 {
    let tau = std::f64::consts::TAU;
    let forward = (end - start).rem_euclid(tau);
    if clockwise {
        if forward == 0.0 {
            -tau
        } else {
            forward - tau
        }
    } else if forward == 0.0 {
        tau
    } else {
        forward
    }
}

/// Return ABB `MoveC`'s `CirPoint`: a point on the requested arc, halfway through its sweep.
///
/// ABB's first `MoveC` target is not the circle centre. Start → `CirPoint` → end determines the
/// circle and the direction, so the midpoint must lie on the requested CW/CCW sweep. The
/// refusals below are exact representability checks, not tolerance-bearing geometry policy.
fn circular_point(
    segment: &Segment,
    start: [f64; 3],
    end: [f64; 3],
) -> Result<[f64; 3], CodecError> {
    let [cx, cy] = segment
        .centre
        .ok_or_else(|| CodecError::Other("RAPID arc segment is missing its centre".to_string()))?;
    let (cx, cy) = (cx.value(), cy.value());
    let [sx, sy, sz] = start;
    let [ex, ey, ez] = end;

    for (name, value) in [
        ("start X", sx),
        ("start Y", sy),
        ("start Z", sz),
        ("end X", ex),
        ("end Y", ey),
        ("end Z", ez),
        ("centre X", cx),
        ("centre Y", cy),
    ] {
        if !value.is_finite() {
            return Err(CodecError::Other(format!(
                "cannot emit RAPID arc with non-finite {name} ({value})"
            )));
        }
    }
    if ez != sz {
        return Err(CodecError::Other(format!(
            "RAPID MoveC cannot emit an arc that rises from Z {sz} to Z {ez}"
        )));
    }
    if ex == sx && ey == sy {
        return Err(CodecError::Other(
            "RAPID MoveC cannot emit a full-turn arc whose end equals its start".to_string(),
        ));
    }

    let radius = libm::hypot(sx - cx, sy - cy);
    if !(radius.is_finite() && radius > 0.0) {
        return Err(CodecError::Other(format!(
            "RAPID arc has a non-finite or zero start radius ({radius})"
        )));
    }

    let start_angle = libm::atan2(sy - cy, sx - cx);
    let end_angle = libm::atan2(ey - cy, ex - cx);
    let middle = start_angle + signed_sweep(start_angle, end_angle, segment.clockwise) / 2.0;
    Ok([
        cx + radius * libm::cos(middle),
        cy + radius * libm::sin(middle),
        sz,
    ])
}

/// Emits an ABB RAPID program from a stream of IR segments.
pub fn emit_rapid_to_writer<I, W>(
    segments: I,
    params: &EmitParams,
    writer: &mut W,
) -> Result<(), CodecError>
where
    I: IntoIterator<Item = Result<Segment, CodecError>>,
    W: Write,
{
    if params.cnc_frame.is_some() {
        return Err(CodecError::Other(
            "RAPID emit cannot carry cnc_frame: CNC WCS/tool/spindle/coolant fields are not ABB workobject/tooldata frames"
                .to_string(),
        ));
    }

    writeln!(writer, "MODULE DryProgram").map_err(|e| CodecError::Other(e.to_string()))?;
    writeln!(writer, "  ! Generated by Dry (DryMachina) Robotic Engine")
        .map_err(|e| CodecError::Other(e.to_string()))?;
    writeln!(writer, "  ! Coordinate System: Base / Tool0")
        .map_err(|e| CodecError::Other(e.to_string()))?;
    writeln!(writer, "  PROC main()").map_err(|e| CodecError::Other(e.to_string()))?;
    writeln!(writer, "    ConfL \\Off;").map_err(|e| CodecError::Other(e.to_string()))?;
    writeln!(writer, "    ConfJ \\Off;").map_err(|e| CodecError::Other(e.to_string()))?;

    let mut programmed_position = [0.0; 3];

    for item in segments {
        let seg = item?;
        if seg.kind == SegmentKind::Dwell {
            if let Some(secs) = seg.dwell_s {
                if !secs.is_finite() {
                    return Err(CodecError::Other(format!(
                        "cannot emit non-finite dwell ({secs}) as RAPID WaitTime"
                    )));
                }
                writeln!(writer, "    WaitTime {secs:.3};")
                    .map_err(|e| CodecError::Other(e.to_string()))?;
            }
            continue;
        }

        let mut start = programmed_position;
        for (index, axis) in ["X", "Y", "Z"].into_iter().enumerate() {
            if let Some(value) = seg.start[index] {
                let value = value.value();
                if !value.is_finite() {
                    return Err(CodecError::Other(format!(
                        "cannot emit non-finite RAPID start {axis} ({value})"
                    )));
                }
                start[index] = value;
            }
        }
        let mut end = start;
        for (index, axis) in ["X", "Y", "Z"].into_iter().enumerate() {
            if let Some(value) = seg.end[index] {
                let value = value.value();
                if !value.is_finite() {
                    return Err(CodecError::Other(format!(
                        "cannot emit non-finite RAPID end {axis} ({value})"
                    )));
                }
                end[index] = value;
            }
        }
        if seg.kind == SegmentKind::Arc && (seg.end[0].is_none() || seg.end[1].is_none()) {
            return Err(CodecError::Other(
                "RAPID arc segment needs an explicit end X and Y".to_string(),
            ));
        }
        programmed_position = end;

        let speed = seg.speed.value();
        if !speed.is_finite() {
            return Err(CodecError::Other(format!(
                "cannot emit non-finite RAPID speed ({speed})"
            )));
        }
        let speed = speed.max(1.0);
        let speed_str = format!("v{:.0}", speed.round());

        let orientation = unit_orientation(seg.orientation)
            .map_err(|error| CodecError::Other(format!("cannot emit RAPID segment: {error}")))?;
        let [q1, q2, q3, q4] = quaternion_from_direction(orientation);

        match seg.kind {
            SegmentKind::Line => {
                let [end_x, end_y, end_z] = end;
                let zone = if seg.travel { "z50" } else { "fine" };
                writeln!(
                    writer,
                    "    MoveL [[{end_x:.3}, {end_y:.3}, {end_z:.3}], [{q1:.6}, {q2:.6}, {q3:.6}, {q4:.6}], [0, 0, 0, 0], [9E9, 9E9, 9E9, 9E9, 9E9, 9E9]], {speed_str}, {zone}, tool0\\WObj:=wobj0;"
                )
                .map_err(|e| CodecError::Other(e.to_string()))?;
            }
            SegmentKind::Arc => {
                let [circle_x, circle_y, circle_z] = circular_point(&seg, start, end)?;
                let [end_x, end_y, end_z] = end;
                writeln!(
                    writer,
                    "    MoveC [[{circle_x:.3}, {circle_y:.3}, {circle_z:.3}], [{q1:.6}, {q2:.6}, {q3:.6}, {q4:.6}], [0, 0, 0, 0], [9E9, 9E9, 9E9, 9E9, 9E9, 9E9]], [[{end_x:.3}, {end_y:.3}, {end_z:.3}], [{q1:.6}, {q2:.6}, {q3:.6}, {q4:.6}], [0, 0, 0, 0], [9E9, 9E9, 9E9, 9E9, 9E9, 9E9]], {speed_str}, fine, tool0\\WObj:=wobj0;"
                )
                .map_err(|e| CodecError::Other(e.to_string()))?;
            }
            _ => {}
        }
    }

    writeln!(writer, "  ENDPROC").map_err(|e| CodecError::Other(e.to_string()))?;
    writeln!(writer, "ENDMODULE").map_err(|e| CodecError::Other(e.to_string()))?;

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::{emit_rapid_to_writer, quaternion_from_direction};
    use crate::emit::{CncFrame, EmitParams, FirmwareFlavor};

    #[test]
    fn quaternion_for_aligned_direction_is_identity() {
        assert_eq!(
            quaternion_from_direction([0.0, 0.0, 1.0]),
            [1.0, 0.0, 0.0, 0.0]
        );
    }

    #[test]
    fn quaternion_for_antipodal_direction_is_half_turn_about_x() {
        assert_eq!(
            quaternion_from_direction([0.0, 0.0, -1.0]),
            [0.0, 1.0, 0.0, 0.0]
        );
    }

    #[test]
    fn quaternion_for_general_direction_has_expected_components() {
        let actual = quaternion_from_direction([0.6, 0.0, 0.8]);
        let expected = [0.9486832980505138, 0.0, 0.31622776601683794, 0.0];
        for (actual, expected) in actual.into_iter().zip(expected) {
            assert!((actual - expected).abs() < 1e-15, "{actual} != {expected}");
        }
        assert_eq!(actual[1].to_bits(), 0.0f64.to_bits(), "zero is canonical");
    }

    #[test]
    fn cnc_frame_is_refused_before_any_module_bytes_are_written() {
        let params = EmitParams {
            flavor: FirmwareFlavor::Rapid,
            cnc_frame: Some(CncFrame::default()),
            ..EmitParams::default()
        };
        let mut output = Vec::new();
        let error = emit_rapid_to_writer(
            std::iter::empty::<Result<crate::ir::Segment, crate::codec::CodecError>>(),
            &params,
            &mut output,
        )
        .expect_err("RAPID must not silently drop a CNC frame")
        .to_string();
        assert!(error.contains("cannot carry cnc_frame"), "{error}");
        assert!(
            output.is_empty(),
            "the refusal must precede the MODULE header"
        );
    }
}
