//! ABB RAPID Robot Program Emission.
//!
//! Generates modular, standard ABB RAPID code (`.mod`) with robtarget positions,
//! quaternion orientations `[q1, q2, q3, q4]`, speeddata, zonedata,
//! and MoveL / MoveC instructions.

use super::EmitParams;
use crate::codec::CodecError;
use crate::ir::{Segment, SegmentKind};
use std::io::Write;

/// Convert a 3D unit direction vector to a quaternion [w, x, y, z] (representing rotation from [0,0,1]).
pub fn quaternion_from_direction(dir: [f64; 3]) -> [f64; 4] {
    let [dx, dy, dz] = dir;
    if dz > 0.999999 {
        [1.0, 0.0, 0.0, 0.0]
    } else if dz < -0.999999 {
        [0.0, 1.0, 0.0, 0.0]
    } else {
        let w = 1.0 + dz;
        let x = -dy;
        let y = dx;
        let z = 0.0;
        let norm = (w * w + x * x + y * y + z * z).sqrt();
        [w / norm, x / norm, y / norm, z / norm]
    }
}

/// Emits an ABB RAPID program from a stream of IR segments.
pub fn emit_rapid_to_writer<I, W>(
    segments: I,
    _params: &EmitParams,
    writer: &mut W,
) -> Result<(), CodecError>
where
    I: IntoIterator<Item = Result<Segment, CodecError>>,
    W: Write,
{
    writeln!(writer, "MODULE DryProgram").map_err(|e| CodecError::Other(e.to_string()))?;
    writeln!(writer, "  ! Generated by Dry (DryMachina) Robotic Engine")
        .map_err(|e| CodecError::Other(e.to_string()))?;
    writeln!(writer, "  ! Coordinate System: Base / Tool0")
        .map_err(|e| CodecError::Other(e.to_string()))?;
    writeln!(writer, "  PROC main()").map_err(|e| CodecError::Other(e.to_string()))?;
    writeln!(writer, "    ConfL \\Off;").map_err(|e| CodecError::Other(e.to_string()))?;
    writeln!(writer, "    ConfJ \\Off;").map_err(|e| CodecError::Other(e.to_string()))?;

    let mut cur_x = 0.0;
    let mut cur_y = 0.0;
    let mut cur_z = 0.0;

    for item in segments {
        let seg = item?;
        if seg.kind == SegmentKind::Dwell {
            if let Some(secs) = seg.dwell_s {
                writeln!(writer, "    WaitTime {secs:.3};")
                    .map_err(|e| CodecError::Other(e.to_string()))?;
            }
            continue;
        }

        if let Some(x) = seg.end[0] {
            cur_x = x.value();
        }
        if let Some(y) = seg.end[1] {
            cur_y = y.value();
        }
        if let Some(z) = seg.end[2] {
            cur_z = z.value();
        }

        let speed = seg.speed.value().max(1.0);
        let speed_str = format!("v{:.0}", speed.round());

        let [q1, q2, q3, q4] = if let Some(orient) = seg.orientation {
            quaternion_from_direction(orient)
        } else {
            [1.0, 0.0, 0.0, 0.0]
        };

        match seg.kind {
            SegmentKind::Line => {
                let zone = if seg.travel { "z50" } else { "fine" };
                writeln!(
                    writer,
                    "    MoveL [[{cur_x:.3}, {cur_y:.3}, {cur_z:.3}], [{q1:.6}, {q2:.6}, {q3:.6}, {q4:.6}], [0, 0, 0, 0], [9E9, 9E9, 9E9, 9E9, 9E9, 9E9]], {speed_str}, {zone}, tool0\\WObj:=wobj0;"
                )
                .map_err(|e| CodecError::Other(e.to_string()))?;
            }
            SegmentKind::Arc => {
                let zone = "fine";
                let cx = seg.centre.map(|c| c[0].value()).unwrap_or(cur_x);
                let cy = seg.centre.map(|c| c[1].value()).unwrap_or(cur_y);
                let cz = cur_z;
                writeln!(
                    writer,
                    "    MoveC [[{cx:.3}, {cy:.3}, {cz:.3}], [{q1:.6}, {q2:.6}, {q3:.6}, {q4:.6}], [0, 0, 0, 0], [9E9, 9E9, 9E9, 9E9, 9E9, 9E9]], [[{cur_x:.3}, {cur_y:.3}, {cur_z:.3}], [{q1:.6}, {q2:.6}, {q3:.6}, {q4:.6}], [0, 0, 0, 0], [9E9, 9E9, 9E9, 9E9, 9E9, 9E9]], {speed_str}, {zone}, tool0\\WObj:=wobj0;"
                )
                .map_err(|e| CodecError::Other(e.to_string()))?;
            }
            _ => {}
        }
    }

    writeln!(writer, "  ENDPROC").map_err(|e| CodecError::Other(e.to_string()))?;
    writeln!(writer, "ENDMODULE").map_err(|e| CodecError::Other(e.to_string()))?;

    Ok(())
}
