MODULE DryProgram
  ! Generated by Dry (DryMachina) Robotic Engine
  ! Coordinate System: Base / Tool0
  PROC main()
    ConfL \Off;
    ConfJ \Off;
    MoveL [[10.000, 0.000, 5.000], [1.000000, 0.000000, 0.000000, 0.000000], [0, 0, 0, 0], [9E9, 9E9, 9E9, 9E9, 9E9, 9E9]], v3000, z50, tool0\WObj:=wobj0;
    MoveL [[20.000, 0.000, 5.000], [1.000000, 0.000000, 0.000000, 0.000000], [0, 0, 0, 0], [9E9, 9E9, 9E9, 9E9, 9E9, 9E9]], v1200, fine, tool0\WObj:=wobj0;
    MoveC [[27.071, 2.929, 5.000], [0.948683, 0.000000, 0.316228, 0.000000], [0, 0, 0, 0], [9E9, 9E9, 9E9, 9E9, 9E9, 9E9]], [[30.000, 10.000, 5.000], [0.948683, 0.000000, 0.316228, 0.000000], [0, 0, 0, 0], [9E9, 9E9, 9E9, 9E9, 9E9, 9E9]], v1200, fine, tool0\WObj:=wobj0;
    WaitTime 1.500;
    MoveL [[30.000, 20.000, 5.000], [0.707107, 0.707107, 0.000000, 0.000000], [0, 0, 0, 0], [9E9, 9E9, 9E9, 9E9, 9E9, 9E9]], v600, fine, tool0\WObj:=wobj0;
  ENDPROC
ENDMODULE
