//! Conformance: Dry `simulate` must reproduce the FullControl oracle's metrics on every fixture under
//! `conformance/simulate/` (generated by `conformance/oracle/gen_simulate.py`). Clean-room: we match the
//! oracle's *outputs*, not its code (`docs/CLEANROOM.md`).

use dry_core::{simulate, Metrics, Toolpath};
use serde::Deserialize;
use std::fs;
use std::path::PathBuf;

#[derive(Deserialize)]
struct Fixture {
    design: String,
    ir: Toolpath,
    expected: Metrics,
}

fn corpus_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../conformance/simulate")
}

/// Relative+absolute float comparison (cross-language sums can differ by a few ULP).
fn close(a: f64, b: f64) -> bool {
    let d = (a - b).abs();
    d <= 1e-9 || d <= 1e-9 * a.abs().max(b.abs())
}

fn check(name: &str, got: &Metrics, want: &Metrics) {
    let fields: [(&str, f64, f64); 8] = [
        ("total_time_s", got.total_time_s, want.total_time_s),
        ("print_time_s", got.print_time_s, want.print_time_s),
        ("travel_time_s", got.travel_time_s, want.travel_time_s),
        (
            "extruding_distance",
            got.extruding_distance,
            want.extruding_distance,
        ),
        ("travel_distance", got.travel_distance, want.travel_distance),
        ("extruded_volume", got.extruded_volume, want.extruded_volume),
        ("filament_length", got.filament_length, want.filament_length),
        ("max_flow_rate", got.max_flow_rate, want.max_flow_rate),
    ];
    for (field, g, w) in fields {
        assert!(close(g, w), "[{name}] {field}: got {g}, oracle {w}");
    }
    assert_eq!(
        got.segment_count, want.segment_count,
        "[{name}] segment_count"
    );
}

#[test]
fn simulate_matches_the_fullcontrol_oracle() {
    let dir = corpus_dir();
    let mut checked = 0;
    for entry in fs::read_dir(&dir).expect("conformance/simulate exists") {
        let path = entry.unwrap().path();
        if path.extension().and_then(|e| e.to_str()) != Some("json") {
            continue;
        }
        let fx: Fixture = serde_json::from_str(&fs::read_to_string(&path).unwrap())
            .unwrap_or_else(|e| panic!("parse {path:?}: {e}"));
        let got = simulate(&fx.ir);
        check(&fx.design, &got, &fx.expected);
        checked += 1;
    }
    assert!(checked >= 1, "no fixtures found in {dir:?}");
    eprintln!("simulate conformance: {checked} fixtures matched the FullControl oracle");
}
