//! Conformance: Dry `emit` must reproduce the FullControl oracle's motion g-code **byte-for-byte** on
//! every fixture under `conformance/gcode/` (generated by `conformance/oracle/gen.py`). This is the
//! strictest gate. Clean-room: we match the oracle's *output*, not its code (`docs/CLEANROOM.md`).

use dry_core::{emit, EmitParams, Toolpath};
use serde::Deserialize;
use std::fs;
use std::path::PathBuf;

#[derive(Deserialize)]
struct Fixture {
    design: String,
    ir: Toolpath,
    params: EmitParams,
    expected: Vec<String>,
}

fn corpus_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../conformance/gcode")
}

#[test]
fn emit_matches_the_fullcontrol_oracle_byte_for_byte() {
    let dir = corpus_dir();
    let mut checked = 0;
    for entry in fs::read_dir(&dir).expect("conformance/gcode exists") {
        let path = entry.unwrap().path();
        if path.extension().and_then(|e| e.to_str()) != Some("json") {
            continue;
        }
        let fx: Fixture = serde_json::from_str(&fs::read_to_string(&path).unwrap())
            .unwrap_or_else(|e| panic!("parse {path:?}: {e}"));
        let got = emit(&fx.ir, &fx.params);
        assert_eq!(
            got, fx.expected,
            "[{}] g-code mismatch vs the FullControl oracle",
            fx.design
        );
        checked += 1;
    }
    assert!(checked >= 1, "no fixtures found in {dir:?}");
    eprintln!("g-code conformance: {checked} fixtures matched the oracle byte-for-byte");
}
