"""Unit test suite for Dry Slicer Post-Processor."""

import tempfile
from pathlib import Path
from dry_slicer_postprocess import process_gcode_file, parse_slicer_comments

SAMPLE_GCODE = """; generated by OrcaSlicer 2.0.0 on 2026-08-30
; filament_type = PLA
; nozzle_diameter = 0.4
; total_layer_count = 10
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative extrusion
G1 Z0.200 F7800.000
G1 X10.0 Y10.0 E0.5 F1800.0
G1 X50.0 Y10.0 E1.5 F1800.0
G1 X50.0 Y50.0 E1.5 F1800.0
G1 X10.0 Y50.0 E1.5 F1800.0
G1 X10.0 Y10.0 E1.5 F1800.0
M400
M84 ; disable motors
"""


def test_parse_slicer_comments():
    meta = parse_slicer_comments(SAMPLE_GCODE)
    assert meta.get("filament_type") == "PLA"
    assert meta.get("nozzle_diameter") == "0.4"
    assert meta.get("total_layer_count") == "10"


def test_process_gcode_file():
    with tempfile.NamedTemporaryFile("w", suffix=".gcode", delete=False) as f:
        f.write(SAMPLE_GCODE)
        temp_path = f.name

    try:
        res = process_gcode_file(temp_path, verify_contracts=True, generate_report=True)
        assert res["file"] == temp_path
        assert res["size_bytes"] > 0
        assert res["passed"] is True

        # Check report HTML created
        report_file = Path(temp_path).with_suffix(".dry.html")
        assert report_file.exists()
        html_text = report_file.read_text(encoding="utf-8")
        assert "Dry Pre-Flight Safety Verification" in html_text
        assert "VERIFIED SAFE" in html_text
    finally:
        Path(temp_path).unlink(missing_ok=True)
        Path(temp_path).with_suffix(".dry.html").unlink(missing_ok=True)


if __name__ == "__main__":
    test_parse_slicer_comments()
    test_process_gcode_file()
    print("All slicer post-processor tests passed!")
