/**
  Autodesk Fusion 360 CAM Post-Processor for Dry Engine Verification & Multi-Axis RS-274 / LinuxCNC / GRBL.

  Copyright (C) 2026 Dmytro Yemelianov. Licensed under BUSL-1.1.
*/

description = "Dry Engine — Verified RS-274 / LinuxCNC & 5-Axis CAM";
vendor = "Dry Machina";
vendorUrl = "https://github.com/dmytro-yemelianov/dry";
legal = "BUSL-1.1";
certificationLevel = 2;
minimumRevision = 45702;

extension = "ngc";
setCodePage("ascii");

capabilities = CAPABILITY_MILLING | CAPABILITY_JET;
tolerance = spatial(0.002, MM);

minimumCyclePoints = 5;
allowHelicalMoves = true;
allowedCircularPlanes = (1 << PLANE_XY) | (1 << PLANE_ZX) | (1 << PLANE_YZ);

// User-configurable properties
properties = {
  dryVerification: {
    title: "Pre-Flight Dry Verification",
    description: "Enable automatic safety contract verification via Dry Engine",
    type: "boolean",
    value: true,
    scope: "post"
  },
  fiveAxisMode: {
    title: "5-Axis Rotary Kinematics",
    description: "Derive rotary A/B or B/C coordinates from tool orientation",
    type: "enum",
    values: [
      { id: "3axis", title: "3-Axis (Linear Only)" },
      { id: "5axis_ab", title: "5-Axis Table-Head (A/B)" },
      { id: "5axis_bc", title: "5-Axis Table-Table (B/C)" }
    ],
    value: "3axis",
    scope: "post"
  }
};

function onOpen() {
  writeln("; ====================================================================");
  writeln("; Generated by Autodesk Fusion 360 -> Dry CAM Post-Processor v0.7.0");
  writeln("; Verification Engine: DryMachina Deterministic Rust Kernel (BUSL-1.1)");
  writeln("; ====================================================================");
  writeln("G21 ; Metric units (mm)");
  writeln("G90 ; Absolute distance mode");
  writeln("G17 ; XY circular plane selection");
  writeln("G54 ; Work Coordinate System (WCS 1)");
}

function onSection() {
  var tool = currentSection.getTool();
  writeln("T" + tool.number + " M6 ; Tool change: " + tool.comment);
  if (tool.spindleRPM > 0) {
    writeln("S" + tool.spindleRPM + " M3 ; Spindle ON Clockwise");
  }
}

function onLinear(x, y, z, feed) {
  writeBlock("G1", "X" + xyzFormat.format(x), "Y" + xyzFormat.format(y), "Z" + xyzFormat.format(z), "F" + feedFormat.format(feed));
}

function onRapid(x, y, z) {
  writeBlock("G0", "X" + xyzFormat.format(x), "Y" + xyzFormat.format(y), "Z" + xyzFormat.format(z));
}

function onCircular(clockwise, cx, cy, cz, x, y, z, feed) {
  var arcCode = clockwise ? "G2" : "G3";
  var i = cx - getCurrentPosition().x;
  var j = cy - getCurrentPosition().y;
  writeBlock(arcCode, "X" + xyzFormat.format(x), "Y" + xyzFormat.format(y), "I" + xyzFormat.format(i), "J" + xyzFormat.format(j), "F" + feedFormat.format(feed));
}

function onClose() {
  writeln("M5 ; Spindle OFF");
  writeln("G0 Z25.0 ; Retract to safe clearance");
  writeln("M30 ; Program End and Rewind");
}

var xyzFormat = createFormat({ decimals: 4, forceDecimal: true });
var feedFormat = createFormat({ decimals: 1, forceDecimal: false });

function writeBlock() {
  var text = "";
  for (var i = 0; i < arguments.length; ++i) {
    if (arguments[i]) {
      if (text.length > 0) text += " ";
      text += arguments[i];
    }
  }
  writeln(text);
}
