"""Unit test for APT-CL converter."""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from dry_apt_cl_converter import parse_apt_cl_to_dry_ops

SAMPLE_APT = """$$ APT CLDATA generated by Mastercam / Siemens NX
MULTAX / ON
FEDRAT / 1500.0
SPINDL / 12000.0, CLW
GOTO / 0.0, 0.0, 10.0, 0.0, 0.0, 1.0
GOTO / 50.0, 0.0, 10.0, 0.0, 0.7071, 0.7071
DWELL / 1.5
GOTO / 50.0, 50.0, 10.0, 0.0, 0.0, 1.0
"""


def test_parse_apt_cl():
    ops = parse_apt_cl_to_dry_ops(SAMPLE_APT)
    assert len(ops) > 0

    has_orient = any(op.get("op") == "orient" for op in ops)
    assert has_orient is True

    has_dwell = any(op.get("op") == "dwell" and op.get("seconds") == 1.5 for op in ops)
    assert has_dwell is True

    has_speed = any(op.get("op") == "speed" and op.get("print") == 1500.0 for op in ops)
    assert has_speed is True


if __name__ == "__main__":
    test_parse_apt_cl()
    print("APT-CL converter tests passed!")
