#!/usr/bin/env python3
"""Generate or verify the evidence-derived Dry formal-assurance report."""

from __future__ import annotations

import argparse
from collections import Counter
import difflib
from pathlib import Path
import sys
from typing import Any

try:
    import tomllib
except ModuleNotFoundError:  # Python 3.10 and earlier
    import tomli as tomllib


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = REPO_ROOT / "docs" / "assurance" / "01-assurance-sitemap.md"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when the committed report differs from the claim registry",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help="report path (defaults to docs/assurance/01-assurance-sitemap.md)",
    )
    return parser.parse_args()


def load_claims() -> list[dict[str, Any]]:
    claims_path = REPO_ROOT / "proofs" / "claims.toml"
    with claims_path.open("rb") as handle:
        document = tomllib.load(handle)
    claims = document.get("claim")
    if not isinstance(claims, list):
        raise ValueError("proofs/claims.toml: claim must be an array of tables")
    return claims


def repository_link(raw_path: str, *, label: str | None = None) -> str:
    """Return a portable link from docs/assurance to a repository artifact."""
    path = Path(raw_path)
    display = label or path.name
    return f"[`{display}`](../../{path.as_posix()})"


def joined_links(paths: list[str]) -> str:
    return ", ".join(repository_link(path) for path in paths) if paths else "—"


def status_counts(
    claims: list[dict[str, Any]], status_name: str
) -> Counter[str]:
    return Counter(
        claim.get("status", {}).get(status_name, "missing") for claim in claims
    )


def status_summary(counts: Counter[str], order: tuple[str, ...]) -> str:
    return ", ".join(f"`{name}` {counts[name]}" for name in order if counts[name])


def claim_is_implementation_checked(claim: dict[str, Any]) -> bool:
    status = claim.get("status", {})
    return (
        claim.get("scope") == "implementation"
        and status.get("abstract") == "proved"
        and status.get("numeric") in {"bounded", "not-applicable"}
        and status.get("refinement") == "checked"
    )


def bullet_items(values: list[str]) -> list[str]:
    if not values:
        return ["- None recorded."]
    return [f"- {value}" for value in values]


def generate_report(claims: list[dict[str, Any]] | None = None) -> str:
    if claims is None:
        claims = load_claims()

    abstract = status_counts(claims, "abstract")
    numeric = status_counts(claims, "numeric")
    refinement = status_counts(claims, "refinement")
    implementation_claims = [
        claim for claim in claims if claim.get("scope") == "implementation"
    ]
    checked_implementation_claims = [
        claim for claim in claims if claim_is_implementation_checked(claim)
    ]
    numeric_pending = [
        claim for claim in claims if claim.get("status", {}).get("numeric") == "pending"
    ]
    refinement_pending = [
        claim
        for claim in claims
        if claim.get("status", {}).get("refinement") == "pending"
    ]

    lines = [
        "<!-- Generated by tools/generate_assurance_report.py; do not edit by hand. -->",
        "",
        "# Dry formal assurance sitemap",
        "",
        "This report is generated from [`proofs/claims.toml`](../../proofs/claims.toml), "
        "the authoritative claim registry. It deliberately reports the assurance layers "
        "independently: an abstract Lean theorem does **not** establish binary64 behavior, "
        "Rust refinement, target correctness, or physical-machine safety.",
        "",
        "## Registry summary",
        "",
        f"- Registered claims: **{len(claims)}**.",
        f"- Abstract status: {status_summary(abstract, ('proved', 'specified', 'not-applicable', 'missing'))}.",
        f"- Numeric status: {status_summary(numeric, ('bounded', 'empirical', 'pending', 'not-applicable', 'missing'))}.",
        f"- Implementation-refinement status: {status_summary(refinement, ('checked', 'pending', 'not-applicable', 'missing'))}.",
        f"- Implementation-scoped claims meeting all registry gates: "
        f"**{len(checked_implementation_claims)}/{len(implementation_claims)}**.",
        "",
        "The Lean release gate is reproducible with `lake build --wfail`. The job count "
        "printed by Lake is a build-system job count, not a theorem count, so this report "
        "does not present it as proof coverage. Rust tests and mutation manifests are linked "
        "only on claims that register them as refinement evidence.",
        "",
        "## Claim matrix",
        "",
        "| Claim | Scope | Theorem | Spec profile | Relation | Abstract | Numeric | Rust refinement |",
        "| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |",
    ]

    for claim in claims:
        status = claim.get("status", {})
        theorem = claim.get("theorem", "")
        theorem_link = repository_link(
            claim.get("lean_source", ""), label=theorem
        )
        lines.append(
            "| `{id}` | `{scope}` | {theorem} | `{spec}` | `{relation}` | "
            "`{abstract}` | `{numeric}` | `{refinement}` |".format(
                id=claim.get("id", ""),
                scope=claim.get("scope", ""),
                theorem=theorem_link,
                spec=claim.get("spec_version", ""),
                relation=claim.get("relation", ""),
                abstract=status.get("abstract", "missing"),
                numeric=status.get("numeric", "missing"),
                refinement=status.get("refinement", "missing"),
            )
        )

    lines.extend(
        [
            "",
            "## Open registry obligations",
            "",
            "These are derived from explicit `pending` statuses; they are not failures of the "
            "abstract theorems.",
            "",
            f"### Numeric refinement pending ({len(numeric_pending)})",
            "",
        ]
    )
    lines.extend(
        bullet_items(
            [f"`{claim['id']}` — {claim['title']}" for claim in numeric_pending]
        )
    )
    lines.extend(
        [
            "",
            f"### Rust refinement pending ({len(refinement_pending)})",
            "",
        ]
    )
    lines.extend(
        bullet_items(
            [f"`{claim['id']}` — {claim['title']}" for claim in refinement_pending]
        )
    )

    lines.extend(["", "## Claim evidence and boundaries", ""])
    for claim in claims:
        status = claim.get("status", {})
        lines.extend(
            [
                f"### `{claim.get('id', '')}`",
                "",
                claim.get("title", ""),
                "",
                f"- Scope/relation: `{claim.get('scope', '')}` / "
                f"`{claim.get('relation', '')}`.",
                f"- Status: abstract `{status.get('abstract', 'missing')}`, numeric "
                f"`{status.get('numeric', 'missing')}`, Rust refinement "
                f"`{status.get('refinement', 'missing')}`.",
                f"- Spec profile: `{claim.get('spec_version', '')}`; "
                f"`{claim.get('source_dialect', '')}` → "
                f"`{claim.get('target_dialect', '')}`.",
                f"- Numeric domain: {claim.get('numeric_domain', '')}.",
                f"- Lean theorem: "
                f"{repository_link(claim.get('lean_source', ''), label=claim.get('theorem', ''))}.",
                f"- Rust anchors: {joined_links(claim.get('rust_sources', []))}.",
                f"- Numeric evidence: {joined_links(claim.get('numeric_evidence', []))}.",
                f"- Refinement evidence: "
                f"{joined_links(claim.get('refinement_evidence', []))}.",
                "",
                "**Assumptions**",
                "",
            ]
        )
        lines.extend(bullet_items(claim.get("assumptions", [])))
        lines.extend(["", "**Exclusions**", ""])
        lines.extend(bullet_items(claim.get("exclusions", [])))
        lines.append("")

    lines.extend(
        [
            "## Reproduction gates",
            "",
            "```bash",
            "python3 tools/validate_proof_claims.py",
            "python3 tools/validate_numeric_boundaries.py",
            "python3 tools/check_proof_fixtures.py",
            "python3 tools/check_resolve_orientation_mutations.py",
            "python3 tools/check_resolve_channels_mutations.py",
            "python3 tools/check_feature_mutations.py",
            "python3 tools/generate_assurance_report.py --check",
            "(cd formal && lake build --wfail)",
            "cargo test --workspace --all-features --locked",
            "```",
            "",
            "The FM1 program and its still-open exit gates are tracked in "
            "[`docs/21-mathematical-assurance-plan.md`](../21-mathematical-assurance-plan.md).",
            "",
        ]
    )
    return "\n".join(lines)


def check_report(output: Path, expected: str) -> int:
    try:
        actual = output.read_text(encoding="utf-8")
    except OSError as error:
        print(f"error: cannot read assurance report {output}: {error}", file=sys.stderr)
        return 1
    if actual == expected:
        print(f"assurance report: current ({output.relative_to(REPO_ROOT)})")
        return 0
    diff = difflib.unified_diff(
        actual.splitlines(),
        expected.splitlines(),
        fromfile=str(output.relative_to(REPO_ROOT)),
        tofile="generated from proofs/claims.toml",
        lineterm="",
    )
    print("error: assurance report is stale; regenerate it", file=sys.stderr)
    print("\n".join(diff), file=sys.stderr)
    return 1


def main() -> int:
    args = parse_args()
    output = args.output
    if not output.is_absolute():
        output = REPO_ROOT / output
    try:
        content = generate_report()
    except (OSError, ValueError, tomllib.TOMLDecodeError) as error:
        print(f"error: cannot generate assurance report: {error}", file=sys.stderr)
        return 1
    if args.check:
        return check_report(output, content)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(content, encoding="utf-8")
    print(f"generated assurance report: {output.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
