#!/usr/bin/env python3
"""Parse KRL programs with the external ANTLR grammar generated by `tools/krl_check.sh`.

Driver only. It does not contain a grammar and it must never grow one: the whole value of this
check is that the grammar is somebody else's, so Dry cannot quietly relax it to accept whatever the
emitter happens to produce. `krl_check.sh` fetches `kuka/krl.g4` from `antlr/grammars-v4` at a
pinned commit, verifies its SHA-256, runs the ANTLR tool over it, and points this script at the
generated lexer/parser.

Rejection has two forms, mirroring `tools/linuxcnc_check.sh`:

  1. the lexer or parser reported a syntax error;
  2. the file parsed cleanly but contains no motion instruction at all — a `DEF`/`END` wrapper with
     nothing in it is well-formed and worthless, and a check that passed it would be measuring
     nothing. `linuxcnc_check.sh` treats "interpreted without emitting any canonical operation" as a
     rejection for exactly this reason.

Usage: krl_parse.py --gen <generated-parser-dir> [--verbose] FILE...
Exit:  0 all accepted, 1 one or more rejected, 2 usage or environment error.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

# Motion instructions, by lexer token name. A parse succeeded before these are counted, so a token
# of one of these types can only be the head of a motion statement.
MOTION_TOKENS = ("PTP", "PTP_REL", "LIN", "LIN_REL", "CIRC", "CIRC_REL")


def load_grammar(gen_dir: Path):
    sys.path.insert(0, str(gen_dir))
    try:
        import antlr4  # noqa: F401
    except ImportError:
        sys.exit(
            "antlr4 Python runtime not importable; install it with "
            "`pip install antlr4-python3-runtime==<the version krl_check.sh pinned>`"
        )
    try:
        from krlLexer import krlLexer
        from krlParser import krlParser
    except ImportError as exc:
        sys.exit(f"generated KRL parser not importable from {gen_dir}: {exc}")
    return krlLexer, krlParser


def check(path: Path, krl_lexer, krl_parser):
    """Return (errors, motion_count, statement_token_count) for one file."""
    from antlr4 import CommonTokenStream, InputStream
    from antlr4.error.ErrorListener import ErrorListener

    class Collect(ErrorListener):
        def __init__(self):
            self.errors = []

        def syntaxError(self, recognizer, offending, line, col, msg, e):  # noqa: N802
            self.errors.append(f"line {line}:{col} {msg}")

    text = path.read_text(encoding="utf-8", errors="replace")
    # The grammar's `module` rule ends at EOF with the routine's trailing NEWLINE consumed, so a
    # file without a final newline is a parse error that says nothing about the emitter.
    if not text.endswith("\n"):
        text += "\n"

    lexer = krl_lexer(InputStream(text))
    lexer.removeErrorListeners()
    lex_errors = Collect()
    lexer.addErrorListener(lex_errors)

    tokens = CommonTokenStream(lexer)
    parser = krl_parser(tokens)
    parser.removeErrorListeners()
    parse_errors = Collect()
    parser.addErrorListener(parse_errors)
    parser.module()

    tokens.fill()
    names = krl_parser.symbolicNames
    motion = 0
    total = 0
    for tok in tokens.tokens:
        name = names[tok.type] if 0 <= tok.type < len(names) else None
        if name is None:
            continue
        total += 1
        if name in MOTION_TOKENS:
            motion += 1
    return lex_errors.errors + parse_errors.errors, motion, total


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--gen", required=True, type=Path, help="directory holding krlLexer/krlParser")
    ap.add_argument("--verbose", action="store_true")
    ap.add_argument("files", nargs="+", type=Path)
    args = ap.parse_args()

    if not args.gen.is_dir():
        print(f"not a directory: {args.gen}", file=sys.stderr)
        return 2
    krl_lexer, krl_parser = load_grammar(args.gen)

    status = 0
    for path in args.files:
        if not path.is_file():
            print(f"not a file: {path}", file=sys.stderr)
            return 2
        errors, motion, total = check(path, krl_lexer, krl_parser)
        if errors:
            print(f"REJECTED: {path.name}", file=sys.stderr)
            for err in errors[:12]:
                print(f"    {err}", file=sys.stderr)
            if len(errors) > 12:
                print(f"    ... {len(errors) - 12} more", file=sys.stderr)
            status = 1
            continue
        if motion == 0:
            print(
                f"REJECTED: {path.name} parsed without a single motion instruction "
                f"({total} tokens); a KRL module that moves nothing proves nothing",
                file=sys.stderr,
            )
            status = 1
            continue
        print(f"ok: {path.name} ({motion} motion instructions, {total} tokens)")
        if args.verbose:
            print("".join(f"    {line}" for line in path.read_text().splitlines(True)))
    return status


if __name__ == "__main__":
    sys.exit(main())
