name: Codecov

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  upload-codecov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview
      - name: Install cargo-llvm-cov
        run: cargo install cargo-llvm-cov --locked
      - name: Run coverage
        run: |
          cargo llvm-cov --no-report --tests
          cargo llvm-cov report --codecov > coverage.json
      - name: Upload to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: coverage.json
          fail_ci_if_error: true
